export const REQUEST_BOOKS = "REQUEST_BOOKS";
export const REQUEST_BOOKS_SUCCESS = "REQUEST_BOOKS_SUCCESS";
export const REQUEST_BOOKS_FAIL = "REQUEST_BOOKS_FAIL";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";

export const REQUEST_DETAILS = "REQUEST_DETAILS";
export const REQUEST_DETAILS_SUCCESS = "REQUEST_DETAILS_SUCCESS";
export const REQUEST_DETAILS_FAIL = "REQUEST_DETAILS_FAIL";

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";

export const MY_BOOKS_REQUEST = "MY_BOOKS_REQUEST";
export const MY_BOOKS_SUCCESS = "MY_BOOKS_SUCCESS";
export const MY_BOOKS_FAIL = "MY_BOOKS_FAIL";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
