export const REQUEST_BOOKS = "REQUEST_BOOKS";
export const REQUEST_BOOKS_SUCCESS = "REQUEST_BOOKS_SUCCESS";
export const REQUEST_BOOKS_FAIL = "REQUEST_BOOKS_FAIL";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
